name: Master branch actions
run-name: Executing publish actions on `master` branch

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Invoke build
        run: ./gradlew build

      - name: Publish jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: booruchan-sdk-*
          path: sdk/build/libs/*.jar
          retention-days: 1

  Generate-Artifacts:
    needs: Build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check out credentials repository
        uses: actions/checkout@v2
        with:
          repository: booruchan/booruchan-credentials
          path: build/
          ssh-key: ${{ secrets.CREDENTIALS_SSH_PRIVATE_KEY }}

      - name: Assemble and Sign Android Releases
        run: ./gradlew assembleSignedAndroidRelease -Pjks=/build/Booruchan-extensions.jks -Palias=${{ secrets.ANDROID_KEYSTORE_ALIAS }} -Ppass=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Collect Android Signed apks
        run: ./gradlew collectAndroidSignedApks

      - name: Generate deploy metadata file
        run: ./gradlew generateAndroidSignedDeployMetadata

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: build/android/*
          retention-days: 1

  Publish-Artifacts:
    needs: Generate-Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: android-artifacts

      - name: Push to booruchan-artifacts repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ANDROID_GITHUB_TOKEN_API }}
        with:
          source-directory: ./
          destination-github-username: 'booruchan'
          destination-repository-name: 'booruchan-artifacts'
          user-email: mkliverout@gmail.com
          target-branch: master
