name: Release sdk actions
run-name: Executing release for `${{ github.ref_name }}` tag

on:
  push:
    tags:
      - 'sdk-*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Invoke build
        run: ./gradlew build

      - name: Publish jar artifact
        uses: actions/upload-artifact@v2
        with:
          path: sdk/build/libs/booruchan-sdk*.jar
          retention-days: 1

      - name: Display structure of downloaded files
        run: ls -R

  Release-Sdk-Artifact:
    needs: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Collect artifact from the previous job
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release sdk
        uses: ncipollo/release-action@v1
        with:
          draft: true
          artifacts: "release.tar.gz,foo/*.txt"
